// This file is automatically generated. Do not edit.
export const firebaseConfig = {
  apiKey: "AIzaSyAJvZlvvaXMet7Qa9ii9z2rGPn0bsCbSZ0",
  authDomain: "studio-1255391114-f2da5.firebaseapp.com",
  projectId: "studio-1255391114-f2da5",
  storageBucket: "studio-1255391114-f2da5.appspot.com",
  messagingSenderId: "1096630697372",
  appId: "1:1096630697372:web:edf2d703316276e1495c59",
  measurementId: "",
};
